version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello, Circle CI"
      - run: sleep 50
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Hello, nice shoes"
      - run: sleep 45
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
